spring.application.name=petshop

# ใช้ตัวแปร Environment Variables แทนค่าตรงๆ
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# สำคัญ! เปลี่ยนเป็น update เพื่อให้มันสร้างตารางให้ในครั้งแรก (หลังจาก Deploy ผ่านแล้วค่อยเปลี่ยนเป็น validate หรือ none)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security & Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# Error Handling
server.error.include-stacktrace=never
server.error.include-message=always


# spring.application.name=petshop

# # เปลี่ยน URL, Driver และ Dialect เป็นของ PostgreSQL
# spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.username=dbuser
# spring.datasource.password=Passw0rd123

# # JPA / Hibernate
# spring.jpa.hibernate.ddl-auto=none
# # spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # Security & Jackson
# spring.security.user.name=admin
# spring.security.user.password=123456
# spring.jackson.serialization.fail-on-empty-beans=false

# # Error Handling
# server.error.include-stacktrace=never
# server.error.include-message=always



